---
name: CI (latest)

on: push

jobs:
  build:
    name: Shakespeare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: fabasoad/setup-shakespeare-action@v1.0.0
        with:
          version: 0.3.1
      - name: Hello World
        run: shakespeare run hello-world.spl
