---
name: CI (latest)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  unit_tests:
    name: Unit Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.ref }}
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: test
  functional_tests:
    name: Functional Tests
    timeout-minutes: 5
    strategy:
      matrix:
        os: ['ubuntu-latest','windows-latest','macos-latest']
        version: ['0.3.0','0.3.1']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: fabasoad/setup-shakespeare-action@v1.0.2
        with:
          version: ${{ matrix.version }}
      - name: Validate command (non-Windows)
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          [[ $(shakespeare run hello-world.spl) == "Hello World!" ]] || exit 1;
      - name: Validate command (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          $Output = (shakespeare run hello-world.spl) | Out-String
          &{If($Output.Substring(0,12) -ne 'Hello World!') {exit 1}}
