---
name: CI (latest)

on: push

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2.1.0
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: test
  functional_tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: fabasoad/setup-shakespeare-action@v1.0.2
        with:
          version: 0.3.1
      - name: Hello World
        run: shakespeare run hello-world.spl | grep -q 'Hello World!' || exit 1;
